/**
 ******************************************************************************
 * @file    bsp_can.h
 * @brief   CAN hardware primitive layer ¡ª platform-aware.
 *
 * Platform 0 (STM32F4 + CubeMX, default):
 *   - MX_CAN1_Init() in main.c handles GPIO + RCC + first HAL_CAN_Init.
 *   - NVIC priority/enable generated by CubeMX into HAL_CAN_MspInit.
 *   - bsp_can_hw_configure() enables RX FIFO0 interrupt then starts CAN.
 *
 * Platform 1 (bare-metal, no CubeMX):
 *   - bsp_can.c owns full init including GPIO/RCC/NVIC via HAL_CAN_MspInit.
 ******************************************************************************
 */

#ifndef BSP_CAN_H
#define BSP_CAN_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>

/* --------------------------------------------------------------------------
 * Platform selection (override in preprocessor defines if needed)
 *   0 = STM32F4 + CubeMX  (default)
 *   1 = STM32F4 bare-metal
 * --------------------------------------------------------------------------*/
#ifndef BSP_CAN_PLATFORM
  #define BSP_CAN_PLATFORM  0
#endif

#if (BSP_CAN_PLATFORM == 0 || BSP_CAN_PLATFORM == 1)
  #include "stm32f4xx_hal.h"
#endif

#if (BSP_CAN_PLATFORM == 0)
  #include "can.h"
  extern CAN_HandleTypeDef hcan1;
  #define BSP_CAN_HANDLE   hcan1

#elif (BSP_CAN_PLATFORM == 1)
  extern CAN_HandleTypeDef g_bsp_can_handle;
  #define BSP_CAN_HANDLE   g_bsp_can_handle

  #define BSP_CAN_TX_PORT             GPIOA
  #define BSP_CAN_TX_PIN              GPIO_PIN_12
  #define BSP_CAN_RX_PORT             GPIOA
  #define BSP_CAN_RX_PIN              GPIO_PIN_11
  #define BSP_CAN_TX_CLK_ENABLE()     __HAL_RCC_GPIOA_CLK_ENABLE()
  #define BSP_CAN_RX_CLK_ENABLE()     __HAL_RCC_GPIOA_CLK_ENABLE()
  #define BSP_CAN_CLK_ENABLE()        __HAL_RCC_CAN1_CLK_ENABLE()
  #define BSP_CAN_GPIO_AF             GPIO_AF9_CAN1
  #define BSP_CAN_NVIC_PRIO           5U
  #define BSP_CAN_NVIC_SUBPRIO        0U
#endif

/* --------------------------------------------------------------------------
 * Timing ¡ª 500 Kbps @ APB1 = 42 MHz
 * --------------------------------------------------------------------------*/
#define BSP_CAN_PRESCALER   6U
#define BSP_CAN_BS1         CAN_BS1_7TQ
#define BSP_CAN_BS2         CAN_BS2_6TQ
#define BSP_CAN_SJW         CAN_SJW_1TQ

/* --------------------------------------------------------------------------
 * RX ring buffer depth ¡ª must be power of 2
 * --------------------------------------------------------------------------*/
#define BSP_CAN_RX_BUF_SIZE  16U

/* --------------------------------------------------------------------------
 * Error codes
 * --------------------------------------------------------------------------*/
typedef enum {
    BSP_CAN_HW_OK       =  0,
    BSP_CAN_HW_ERR      = -1,
    BSP_CAN_HW_TIMEOUT  = -2,
    BSP_CAN_HW_EMPTY    = -3,
} bsp_can_hw_err_t;

typedef enum {
    BSP_CAN_HW_MODE_NORMAL   = CAN_MODE_NORMAL,
    BSP_CAN_HW_MODE_LOOPBACK = CAN_MODE_LOOPBACK,
    BSP_CAN_HW_MODE_SILENT   = CAN_MODE_SILENT,
} bsp_can_hw_mode_t;

/* --------------------------------------------------------------------------
 * Hardware primitive API
 * --------------------------------------------------------------------------*/
bsp_can_hw_err_t bsp_can_hw_configure(bsp_can_hw_mode_t mode);
bsp_can_hw_err_t bsp_can_hw_stop(void);
bsp_can_hw_err_t bsp_can_hw_set_filter(uint32_t filter_id, uint32_t filter_mask,
                                        uint8_t bank, uint8_t fifo);
bsp_can_hw_err_t bsp_can_hw_send(uint32_t id, const uint8_t *data, uint8_t len,
                                  bool is_ext, bool is_rtr);

/* Direct FIFO poll (used by test suite in loopback mode) */
bsp_can_hw_err_t bsp_can_hw_recv(uint32_t *out_id, uint8_t *out_data,
                                  uint8_t *out_len, bool *out_is_ext,
                                  bool *out_is_rtr);
bool             bsp_can_hw_is_rx_pending(void);

/* Interrupt-driven ring buffer read (used in normal operation) */
bsp_can_hw_err_t bsp_can_hw_recv_from_buffer(uint32_t *out_id, uint8_t *out_data,
                                              uint8_t *out_len, bool *out_is_ext,
                                              bool *out_is_rtr);
bool             bsp_can_hw_buffer_has_data(void);

#ifdef __cplusplus
}
#endif

#endif /* BSP_CAN_H */