/**
 ******************************************************************************
 * @file    bsp_can.c
 * @brief   CAN hardware primitives �� STM32F4 implementation.
 *
 * RX flow (interrupt-driven):
 *   CAN frame arrives on bus
 *       �� CAN1_RX0_IRQHandler  (generated by CubeMX in stm32f4xx_it.c)
 *       �� HAL_CAN_IRQHandler
 *       �� HAL_CAN_RxFifo0MsgPendingCallback  (implemented here)
 *       �� frame pushed into s_rx_ring[]
 *       �� main loop calls bsp_can_hw_recv_from_buffer() to pop
 ******************************************************************************
 */

#include "bsp_can.h"

/* --------------------------------------------------------------------------
 * Platform 1: BSP owns the handle
 * --------------------------------------------------------------------------*/
#if (BSP_CAN_PLATFORM == 1)
CAN_HandleTypeDef g_bsp_can_handle;
#endif

/* --------------------------------------------------------------------------
 * TX header (reused across send calls)
 * --------------------------------------------------------------------------*/
static CAN_TxHeaderTypeDef s_tx_hdr;
static CAN_RxHeaderTypeDef s_rx_hdr;   /* temp, used inside callback only */

#define TX_TIMEOUT_CNT  0xFFFU

/* --------------------------------------------------------------------------
 * RX ring buffer
 *
 * Written in ISR (HAL_CAN_RxFifo0MsgPendingCallback).
 * Read in main loop (bsp_can_hw_recv_from_buffer).
 *
 * Uses lock-free single-producer / single-consumer pattern:
 *   head = next write index (ISR advances)
 *   tail = next read index  (main loop advances)
 * --------------------------------------------------------------------------*/
typedef struct {
    uint32_t id;
    uint8_t  data[8];
    uint8_t  len;
    bool     is_ext;
    bool     is_rtr;
} CanRxFrame_t;

static volatile CanRxFrame_t s_rx_ring[BSP_CAN_RX_BUF_SIZE];
static volatile uint16_t     s_rx_head = 0U;   /* ISR writes here  */
static volatile uint16_t     s_rx_tail = 0U;   /* main reads here  */

#define RX_BUF_MASK  (BSP_CAN_RX_BUF_SIZE - 1U)   /* requires power-of-2 size */

/* ==========================================================================
 * bsp_can_hw_configure
 * ========================================================================== */
bsp_can_hw_err_t bsp_can_hw_configure(bsp_can_hw_mode_t mode)
{
    HAL_CAN_Stop(&BSP_CAN_HANDLE);

    BSP_CAN_HANDLE.Instance                  = CAN1;
    BSP_CAN_HANDLE.Init.Prescaler            = BSP_CAN_PRESCALER;
    BSP_CAN_HANDLE.Init.Mode                 = (uint32_t)mode;
    BSP_CAN_HANDLE.Init.SyncJumpWidth        = BSP_CAN_SJW;
    BSP_CAN_HANDLE.Init.TimeSeg1             = BSP_CAN_BS1;
    BSP_CAN_HANDLE.Init.TimeSeg2             = BSP_CAN_BS2;
    BSP_CAN_HANDLE.Init.TimeTriggeredMode    = DISABLE;
    BSP_CAN_HANDLE.Init.AutoBusOff           = DISABLE;
    BSP_CAN_HANDLE.Init.AutoWakeUp           = DISABLE;
    BSP_CAN_HANDLE.Init.AutoRetransmission   = ENABLE;
    BSP_CAN_HANDLE.Init.ReceiveFifoLocked    = DISABLE;
    BSP_CAN_HANDLE.Init.TransmitFifoPriority = DISABLE;

    if (HAL_CAN_Init(&BSP_CAN_HANDLE) != HAL_OK)
    {
        return BSP_CAN_HW_ERR;
    }

    if (bsp_can_hw_set_filter(0x0000U, 0x0000U, 0U, 0U) != BSP_CAN_HW_OK)
    {
        return BSP_CAN_HW_ERR;
    }

    /* Enable RX FIFO0 message pending interrupt.
     * NVIC priority already configured by CubeMX in HAL_CAN_MspInit.      */
    __HAL_CAN_ENABLE_IT(&BSP_CAN_HANDLE, CAN_IT_RX_FIFO0_MSG_PENDING);

    if (HAL_CAN_Start(&BSP_CAN_HANDLE) != HAL_OK)
    {
        return BSP_CAN_HW_ERR;
    }
    return BSP_CAN_HW_OK;
}

/* ==========================================================================
 * bsp_can_hw_stop
 * ========================================================================== */
bsp_can_hw_err_t bsp_can_hw_stop(void)
{
    __HAL_CAN_DISABLE_IT(&BSP_CAN_HANDLE, CAN_IT_RX_FIFO0_MSG_PENDING);
    HAL_CAN_Stop(&BSP_CAN_HANDLE);
    return BSP_CAN_HW_OK;
}

/* ==========================================================================
 * bsp_can_hw_set_filter
 * ========================================================================== */
bsp_can_hw_err_t bsp_can_hw_set_filter(uint32_t filter_id,
                                        uint32_t filter_mask,
                                        uint8_t  bank,
                                        uint8_t  fifo)
{
    CAN_FilterTypeDef cfg;
    cfg.FilterBank           = bank;
    cfg.FilterMode           = CAN_FILTERMODE_IDMASK;
    cfg.FilterScale          = CAN_FILTERSCALE_32BIT;
    cfg.FilterIdHigh         = (uint16_t)(filter_id   >> 16U);
    cfg.FilterIdLow          = (uint16_t)(filter_id   & 0xFFFFU);
    cfg.FilterMaskIdHigh     = (uint16_t)(filter_mask >> 16U);
    cfg.FilterMaskIdLow      = (uint16_t)(filter_mask & 0xFFFFU);
    cfg.FilterFIFOAssignment = (fifo == 0U) ? CAN_FILTER_FIFO0 : CAN_FILTER_FIFO1;
    cfg.FilterActivation     = CAN_FILTER_ENABLE;
    cfg.SlaveStartFilterBank = 14U;

    if (HAL_CAN_ConfigFilter(&BSP_CAN_HANDLE, &cfg) != HAL_OK)
    {
        return BSP_CAN_HW_ERR;
    }
    return BSP_CAN_HW_OK;
}

/* ==========================================================================
 * bsp_can_hw_send
 * ========================================================================== */
bsp_can_hw_err_t bsp_can_hw_send(uint32_t       id,
                                  const uint8_t *data,
                                  uint8_t        len,
                                  bool           is_ext,
                                  bool           is_rtr)
{
    if (is_ext)
    {
        s_tx_hdr.IDE   = CAN_ID_EXT;
        s_tx_hdr.ExtId = id;
        s_tx_hdr.StdId = 0U;
    }
    else
    {
        s_tx_hdr.IDE   = CAN_ID_STD;
        s_tx_hdr.StdId = id;
        s_tx_hdr.ExtId = 0U;
    }
    s_tx_hdr.RTR                = is_rtr ? CAN_RTR_REMOTE : CAN_RTR_DATA;
    s_tx_hdr.DLC                = len;
    s_tx_hdr.TransmitGlobalTime = DISABLE;

    uint32_t tx_mailbox = CAN_TX_MAILBOX0;
    if (HAL_CAN_AddTxMessage(&BSP_CAN_HANDLE, &s_tx_hdr,
                              (uint8_t *)data, &tx_mailbox) != HAL_OK)
    {
        return BSP_CAN_HW_ERR;
    }

    uint16_t cnt = 0U;
    while (HAL_CAN_GetTxMailboxesFreeLevel(&BSP_CAN_HANDLE) != 3U)
    {
        if (++cnt > TX_TIMEOUT_CNT)
        {
            HAL_CAN_AbortTxRequest(&BSP_CAN_HANDLE, tx_mailbox);
            return BSP_CAN_HW_TIMEOUT;
        }
    }
    return BSP_CAN_HW_OK;
}

/* ==========================================================================
 * bsp_can_hw_recv  �� direct FIFO poll (loopback test only)
 * ========================================================================== */
bsp_can_hw_err_t bsp_can_hw_recv(uint32_t *out_id,
                                  uint8_t  *out_data,
                                  uint8_t  *out_len,
                                  bool     *out_is_ext,
                                  bool     *out_is_rtr)
{
    if (HAL_CAN_GetRxFifoFillLevel(&BSP_CAN_HANDLE, CAN_RX_FIFO0) == 0U)
    {
        return BSP_CAN_HW_EMPTY;
    }
    if (HAL_CAN_GetRxMessage(&BSP_CAN_HANDLE, CAN_RX_FIFO0,
                              &s_rx_hdr, out_data) != HAL_OK)
    {
        return BSP_CAN_HW_ERR;
    }
    *out_is_ext = (s_rx_hdr.IDE == CAN_ID_EXT);
    *out_is_rtr = (s_rx_hdr.RTR == CAN_RTR_REMOTE);
    *out_len    = (uint8_t)s_rx_hdr.DLC;
    *out_id     = *out_is_ext ? s_rx_hdr.ExtId : s_rx_hdr.StdId;
    return BSP_CAN_HW_OK;
}

bool bsp_can_hw_is_rx_pending(void)
{
    return (HAL_CAN_GetRxFifoFillLevel(&BSP_CAN_HANDLE, CAN_RX_FIFO0) > 0U);
}

/* ==========================================================================
 * HAL_CAN_RxFifo0MsgPendingCallback  �� called from ISR by HAL
 *
 * Keep this as short as possible: read frame, push to ring buffer, return.
 * No printf, no heavy logic.
 * ========================================================================== */
#if USE_CANOPEN == DISABLE
void HAL_CAN_RxFifo0MsgPendingCallback(CAN_HandleTypeDef *hcan)
#else
void HAL_CAN_RxFifo0MsgPendingCallback_BSP(CAN_HandleTypeDef *hcan)
#endif
{
    if (hcan->Instance != CAN1) { return; }

    CAN_RxHeaderTypeDef hdr;
    uint8_t             raw[8] = {0};

    if (HAL_CAN_GetRxMessage(hcan, CAN_RX_FIFO0, &hdr, raw) != HAL_OK)
    {
        return;
    }

    /* Check for buffer full �� drop frame rather than corrupt the buffer */
    uint16_t next_head = (s_rx_head + 1U) & RX_BUF_MASK;
    if (next_head == s_rx_tail)
    {
        /* Buffer full �� frame dropped. Increase BSP_CAN_RX_BUF_SIZE if this
         * happens in practice (add a drop counter here for debugging).      */
        return;
    }

    volatile CanRxFrame_t *slot = &s_rx_ring[s_rx_head];
    slot->is_ext = (hdr.IDE == CAN_ID_EXT);
    slot->is_rtr = (hdr.RTR == CAN_RTR_REMOTE);
    slot->len    = (uint8_t)hdr.DLC;
    slot->id     = slot->is_ext ? hdr.ExtId : hdr.StdId;

    for (uint8_t i = 0; i < slot->len; i++)
    {
        slot->data[i] = raw[i];
    }

    /* Advance head �� must be last write (acts as publish barrier) */
    s_rx_head = next_head;
}

/* ==========================================================================
 * bsp_can_hw_recv_from_buffer �� pop one frame from ring buffer (main loop)
 * ========================================================================== */
bsp_can_hw_err_t bsp_can_hw_recv_from_buffer(uint32_t *out_id,
                                              uint8_t  *out_data,
                                              uint8_t  *out_len,
                                              bool     *out_is_ext,
                                              bool     *out_is_rtr)
{
    if (s_rx_tail == s_rx_head)
    {
        return BSP_CAN_HW_EMPTY;
    }

    const volatile CanRxFrame_t *slot = &s_rx_ring[s_rx_tail];
    *out_id     = slot->id;
    *out_is_ext = slot->is_ext;
    *out_is_rtr = slot->is_rtr;
    *out_len    = slot->len;

    for (uint8_t i = 0; i < slot->len; i++)
    {
        out_data[i] = slot->data[i];
    }

    /* Advance tail �� must be last (acts as consume barrier) */
    s_rx_tail = (s_rx_tail + 1U) & RX_BUF_MASK;

    return BSP_CAN_HW_OK;
}

bool bsp_can_hw_buffer_has_data(void)
{
    return (s_rx_tail != s_rx_head);
}

/* ==========================================================================
 * Platform 1 only: HAL_CAN_MspInit
 * ========================================================================== */
#if (BSP_CAN_PLATFORM == 1)
void HAL_CAN_MspInit(CAN_HandleTypeDef *hcan)
{
    if (hcan->Instance == CAN1)
    {
        BSP_CAN_TX_CLK_ENABLE();
        BSP_CAN_RX_CLK_ENABLE();
        BSP_CAN_CLK_ENABLE();

        GPIO_InitTypeDef gpio = {0};
        gpio.Pin       = BSP_CAN_TX_PIN;
        gpio.Mode      = GPIO_MODE_AF_PP;
        gpio.Pull      = GPIO_PULLUP;
        gpio.Speed     = GPIO_SPEED_FREQ_HIGH;
        gpio.Alternate = BSP_CAN_GPIO_AF;
        HAL_GPIO_Init(BSP_CAN_TX_PORT, &gpio);

        gpio.Pin = BSP_CAN_RX_PIN;
        HAL_GPIO_Init(BSP_CAN_RX_PORT, &gpio);

        HAL_NVIC_SetPriority(CAN1_RX0_IRQn, BSP_CAN_NVIC_PRIO, BSP_CAN_NVIC_SUBPRIO);
        HAL_NVIC_EnableIRQ(CAN1_RX0_IRQn);
    }
}
#endif